"""add credenciales

Revision ID: 07f3a2efa6f9
Revises: aa3667002e43
Create Date: 2025-06-11 07:40:56.523353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f3a2efa6f9'
down_revision: Union[str, None] = 'aa3667002e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=True),
    sa.Column('numero_cedula', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('contrasena', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_cedula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credenciales')
    # ### end Alembic commands ###
