"""tarjeton:fix

Revision ID: 437be8026cde
Revises: 
Create Date: 2025-06-04 10:13:07.220840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437be8026cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=True),
    sa.Column('numero_cedula', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('contrasena', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_cedula')
    )
    op.create_table('votaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjeton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacion_id', sa.Integer(), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('partido_politico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['votacion_id'], ['votaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votante_id', sa.Integer(), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['tarjeton.id'], ),
    sa.ForeignKeyConstraint(['votante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('tarjeton')
    op.drop_table('votaciones')
    op.drop_table('credenciales')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
