"""all_tables

Revision ID: b7ffbecc08bd
Revises: 
Create Date: 2025-06-03 11:04:33.667605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ffbecc08bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('contraseña', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacion_id', sa.Integer(), nullable=True),
    sa.Column('texto_opcion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['votacion_id'], ['votaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=True),
    sa.Column('opcion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opcion_id'], ['opciones.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('opciones')
    op.drop_table('votaciones')
    op.drop_table('usuarios')
    op.drop_table('credenciales')
    # ### end Alembic commands ###
