"""add tarjeton

Revision ID: d9215c6f24c9
Revises: 07f3a2efa6f9
Create Date: 2025-06-11 07:57:16.095144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9215c6f24c9'
down_revision: Union[str, None] = '07f3a2efa6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjeton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacion_id', sa.Integer(), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('partido_politico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['votacion_id'], ['votaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarjeton')
    op.drop_table('votaciones')
    # ### end Alembic commands ###
