"""all_tables

Revision ID: e14693d2b680
Revises: b7ffbecc08bd
Create Date: 2025-06-03 11:12:21.762065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14693d2b680'
down_revision: Union[str, None] = 'b7ffbecc08bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'credenciales', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credenciales', type_='foreignkey')
    # ### end Alembic commands ###
