"""add enums

Revision ID: e77c9fe0895a
Revises: d9215c6f24c9
Create Date: 2025-06-11 09:04:32.572964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e77c9fe0895a'
down_revision: Union[str, None] = 'd9215c6f24c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votante_id', sa.Integer(), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['tarjeton.id'], ),
    sa.ForeignKeyConstraint(['votante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('credenciales', 'tipo_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('Usu', 'Admin', name='tipousuario'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credenciales', 'tipo_usuario',
               existing_type=sa.Enum('Usu', 'Admin', name='tipousuario'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_table('votos')
    # ### end Alembic commands ###
